#!/usr/bin/env python3

REMOVAL = "godaftern4chmuiy,spr,bls.yvwd.-e,t,s,e.zqkjt,l.n.u."

TEXT = """GOOD AFTERNOON 4CHAN COMMUNITY,

IT HAS COME TO OUR ATTENTION THAT THIS FORUM
HAS GAINED A REPUTATION FOR, TO PUT IT BLUNTLY,
UTTER RANDOMNESS. IT IS IN THIS TYPE OF
ENVIRONMENT THAT WE BELEIVE PEOPLE OF GREAT
INTELLIGENCE CAN BE FOUND. THIS MAY SEEM
COUNTER-INTUITIVE, BUT BEAR WITH US. THE MIND IS
A DIFFICULT THING TO MEASURE BASED UPON
OUTWARD COMMUNICATIONS. GIVEN STRUCTURED
PRACTICE, EVEN THE MOST FEEBLE MINDED CAN SEEM
INTELLIGENT. THEREFORE, THE MORE FEEBLE-MINDED
ONE IS, THE GREATER OUTWARD STRUCTURE THEY
CRAVE. 4CHAN IS THE VERY ANTITHESIS OF THIS. OUR
ORGANIZATION HAS DEEMED BEING ABLE TO MENTALLY
HANDLE CHAOS AS THE PRIMARY QUALITY IN THOSE
WE SEEK TO JOIN US. HOWEVER, THERE ARE THOSE
AROUND YOU WHO DON'T SHARE YOUR MENTAL
ABILITIES. THE REWARDS AND RISKS OF OUR
ORANIZATION ARE GREAT, SO WE ONLY ACCEPT THOSE
WHO GO BEYOND THEIR FELLOW HUMAN BEINGS.
THEREFORE WE HAVE CREATED A LITTLE PUZZLE IF YOU
WILL. THIS IMAGE IS NOT AS IT SEEMS AND THE TEST
HAS ALREADY BEGUN. THE KEY IS ALL AROUND YOU."""

REMOVED = ""

print(REMOVAL)
removal_idx = 0
for i, c in enumerate(TEXT.lower()):
    if removal_idx > len(REMOVAL) - 1 and not c.isspace():
        REMOVED += c
        continue
    if c.isspace() or (len(REMOVAL) > 0 and c == REMOVAL[removal_idx]):
        removal_idx += 1
        continue
    
    REMOVED += c

print(REMOVED[:120])

